### ISSUE TITLE
Python3: dict.items() vs. dict.iteritems()

### ISSUE THREAD

**Issue by frace** [frace/git-passport#11]
> For performance, you can always use iteritems on dictionaries if you don't need the intermediate list.

Reference: http://codereview.stackexchange.com/a/77176

@Ferada
As far as I know `iteritems()` is gone in Python3 instead `items()` returns an iterator now. See:
- https://docs.python.org/3.4/library/stdtypes.html#dict-views
- http://stackoverflow.com/a/10458567
- http://stackoverflow.com/a/13998534

**Comment by Ferada** [comment]
Ah, my bad.

**Comment by frace** [comment]
Btw. I already fixed some issues you mentioned. I marked and will mark all of those as `code review` and reference your original review.
So if you want to you are able to follow the process and are able to comment if you feel like. :)

**Comment by Ferada** [comment]
Yeah, yeah I saw them :+1:. I'll try out the program and see if I can contribute later.

**Comment by frace** [comment]
Nice!
