### ISSUE TITLE
Possibly merge config_read() and config_validate()

### ISSUE THREAD

**Issue by frace** [frace/git-passport#18]
> I'd get rid of the config_validate function and do that in config_read instead, using a separate config_read_passport or so, which then uses ConfigParser.getboolean and the other get... functions with a very strict schema, so you make sure that everything coming out of the config object is properly parsed. That way you have to write less verification code (as the ConfigParser object takes care of that for you) and you can spend that on making sure that the individual passports have the correct format before handing them off to the rest of the application.

Reference: http://codereview.stackexchange.com/a/77176

@Ferada
Do you talk about to define `config_validate()` as an inner function of `config_read()`?
Possibly would it make sense to transform `config_validate()` into a decorator function which then is used to decorate `config_read()`?

**Comment by Ferada** [comment]
I would change `config_read` to something like the following (of course
still with docstrings and comments):

```
def config_read(filename):
    raw_config = configparser.ConfigParser()
    raw_config.read(filename)

    config = {}
    config["enable_hook"] = raw_config.getboolean("General")
    config["sleep_duration"] = raw_config.getfloat("General")
    ...

    config["git_local_ids"] = {}
    for index, section in enumerate(raw_config.sections()):
        if "Passport" not in section:
            continue

        passport = {}
        passport["email"] = raw_config.get(section, "email")
        ...

        config["git_local_ids"][index] = passport

    return config
```

So, now the structure of the reader is somewhat the same as the
configuration it's reading, verification is immediate and for all read
values (`ConfigParser` raises `ValueError`s if they are malformed;
optionally further verification could be done, i.e. no empty strings,
emails have to have a at-sign, etc.).

And, if you want to keep the check for unknown entries,
`raw_config.remove_option` / `raw_config.remove_section()` after you
extracted all the values from a section, or so, then you can report all
the remaining sections as invalid.

**Comment by frace** [comment]
That's funny. :) Before I checked the code into Git I had something similar setup already. Then I decided to split it up because `McCabe` said the function was too complex. ^^

**Comment by Ferada** [comment]
Heh, yeah, in that case maybe the individual passport reading and reading of the global could each be split off into separate functions (returning a `dict`) so the main function doesn't get too complicated.

**Comment by frace** [comment]
@Ferada
Inside the configparse branch I came up with a solution which is basically a mix between your proposal and what I already had. See commit https://github.com/frace/git-passport/commit/bfddbeafa6a42bc394e8705d1611c37cf8359f82.

I split up config_read() into config_validate_scheme(), config_validate_values() and config_release().

**Comment by frace** [comment]
Closing for now.
