### ISSUE TITLE
Move textwrap.dedent(foo).strip() into its own function

### ISSUE THREAD

**Issue by frace** [frace/git-passport#19]
> textwrap.dedent(foo).strip() is nice, I'm copying that; since you use it very often I think that separate functions, like dedented or so, are in order; something short and simple. Same for lstrip.

Reference: http://codereview.stackexchange.com/a/77176

@Ferada
Do you mean to create a separate function like:

```
def dedented(message, strip_type):
    if strip_type == "strip":
        return textwrap.dedent(message).strip()
    elif strip_type == "lstrip":
        return textwrap.dedent(message).lstrip()
    elif strip_type == "rstrip":
        return textwrap.dedent(message).rstrip()
    else:
        return
```

**Comment by Ferada** [comment]
Hmm, depends, I've created `dedented` and `ldedented` for me because that were the only ones I used. (And `filled`, which also does a `textwrap.fill` afterwards.)

**Comment by frace** [comment]
Fixed with https://github.com/frace/git-passport/commit/7d18de2669d7ff5a92b53db029b45789cf6a4d46

I've added `rstrip()`, might happen that I'll need it sooner or later.
