### ISSUE TITLE
Use less sys.exit() calls

### ISSUE THREAD

**Issue by frace** [frace/git-passport#21]
> Also, I would use less sys.exits in general. It is helpful if you can just import the script for testing purposes and it's jarring if using e.g. config_create suddenly kills the interpreter. Same for proper testing later.

Reference: http://codereview.stackexchange.com/a/77176

@Ferada
I understand the concerns in regards to testing and importing the script in the interpreter. However I just checked where I do call them. The point is that I really need them in situations where the script is used as a Git hook in order to quit a possible commit if something goes wrong with a Git ID/passport.

Unfortunately I don't see a way to reduce the number of calls of `sys.exit()`right now. The only thing I could think of is to introduce a `enable_debug` or `enable_testing` variable which lets us disable the `sys.exit()` calls conditionally.

**Comment by Ferada** [comment]
Sure, fine by me; I'd still personally throw exceptions and exit just on the outermost layer, but I can see why this is useful how it is.

**Comment by frace** [comment]
I'll leave this issue open and will think about it. With the outermost layer I think you talk about `main()`?

**Comment by Ferada** [comment]
Yup.

**Comment by frace** [comment]
@Ferada All fixed ;)
